### ISSUE TITLE
Can't build om master branch

### ISSUE THREAD

**Issue by alectogeek** [vitusortner/floor#208]
If I run `flutter packages pub run build_runner build --delete-conflicting-outputs --verbose` on master (v1.10.14) branch, I see the following problem

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 365ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 19.4s

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Building new asset graph...
[INFO] BuildDefinition:Building new asset graph completed, took 784ms

[INFO] BuildDefinition:Checking for unexpected pre-existing outputs....
[INFO] BuildDefinition:Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Build:Running build...
[INFO] Heartbeat:1.0s elapsed, 0/16 actions completed.
[INFO] Heartbeat:2.0s elapsed, 0/16 actions completed.
[INFO] Heartbeat:3.3s elapsed, 0/16 actions completed.
[INFO] Heartbeat:4.3s elapsed, 0/16 actions completed.
[INFO] Heartbeat:5.5s elapsed, 0/16 actions completed.
[INFO] Heartbeat:6.5s elapsed, 0/16 actions completed.
[INFO] Heartbeat:7.7s elapsed, 0/16 actions completed.
[INFO] Heartbeat:8.7s elapsed, 0/16 actions completed.


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
package:analyzer/src/summary/link.dart 5535:5                     TypeProviderForLink._buildInterfaceType
package:analyzer/src/summary/link.dart 5503:23                    TypeProviderForLink.objectType
package:analyzer/src/summary/link.dart 925:67                     ClassElementForLink_Class._computeInterfaceType
package:analyzer/src/summary/link.dart 823:27                     ClassElementForLink_Class.supertype
package:analyzer/src/task/strong_mode.dart 303:33                 InstanceMemberInferrer._inferClass
package:analyzer/src/task/strong_mode.dart 335:9                  InstanceMemberInferrer._inferClasses
package:analyzer/src/task/strong_mode.dart 56:5                   InstanceMemberInferrer.inferCompilationUnit
package:analyzer/src/summary/link.dart 1627:7                     CompilationUnitElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3840:12                    LibraryElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3540:15                    LibraryCycleNode.link
package:analyzer/src/summary/link.dart 3480:7                     LibraryCycleDependencyWalker.evaluate
package:analyzer/src/summary/link.dart 2213:13                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2179:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2179:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2179:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2179:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2179:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2232:18                    DependencyWalker.walk
package:analyzer/src/summary/link.dart 3513:42                    LibraryCycleForLink.ensureLinked
package:analyzer/src/summary/link.dart 4045:35                    Linker.link
package:analyzer/src/summary/link.dart 311:74                     _relink
package:analyzer/src/summary/link.dart 125:3                      link
package:analyzer/src/dart/analysis/library_context.dart 220:25    LibraryContext.load.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/library_context.dart 219:12    LibraryContext.load
package:analyzer/src/dart/analysis/library_context.dart 98:7      new LibraryContext
package:analyzer/src/dart/analysis/driver.dart 1626:29            AnalysisDriver._createLibraryContext
package:analyzer/src/dart/analysis/driver.dart 1570:26            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 1170:34            AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 2188:24            AnalysisDriverScheduler._run
package:analyzer/src/dart/analysis/driver.dart 2118:5             AnalysisDriverScheduler.start
package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 193:19        BuildOptions.create
package:build_runner/src/generate/build.dart 85:36                build
package:build_runner/src/entrypoint/build.dart 28:24              BuildCommand.run
package:args/command_runner.dart 197:27                           CommandRunner.runCommand
package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
dart:async                                                        new Future.sync
package:args/command_runner.dart 112:14                           CommandRunner.run
package:build_runner/src/entrypoint/run.dart 24:31                run
.dart_tool/build/entrypoint/build.dart 22:22                      main

pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:244:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:267:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:63:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#40     main (file:///Users/alectogeek/Documents/Programs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by alectogeek** [comment]
Are there any news?
