### ISSUE TITLE
Inheritance - mapper set all type as double

### ISSUE THREAD

**Issue by mathieurousseau** [vitusortner/floor#366]
I have inheritance as:
BnEntity => ListEntity => Consequence. 
It almost works, but the mapper generated ignore the fields type and use double for all of them.

```dart
abstract class BnEntity {
  @PrimaryKey(autoGenerate: true)  
  int id;
  int backEndId;
} 

abstract class ListEntity extends BnEntity {
  @ColumnInfo(nullable: false)
  String name;
  String icon;
  int points;
}

@Entity(tableName: 'Consequences')
class Consequence extends ListEntity{

  Consequence(id, name, [ icon = '❓', points = -1 ]);
  Consequence.named({ id, name, icon = '❓' });
  Consequence.empty({ id, icon = '❓', points = -1 });

}
```

But generated mapper:

```dart
  static final _consequencesMapper = (Map<String, dynamic> row) => Consequence(
      row['id'] as double,
      row['name'] as double,
      row['icon'] as double,
      row['points'] as double);
```

```
E/flutter (19240): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'int' is not a subtype of type 'double' in type cast
E/flutter (19240): #0      _$ConsequenceDao._consequencesMapper.<anonymous closure> (package:my_app/db/database.g.dart:272:17)
E/flutter (19240): #1      QueryAdapter.queryList.<anonymous closure> (package:floor/src/adapter/query_adapter.dart:42:36)
E/flutter (19240): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter (19240): #3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
E/flutter (19240): #4      QueryAdapter.queryList (package:floor/src/adapter/query_adapter.dart:42:43)
E/flutter (19240): <asynchronous suspension>
E/flutter (19240): #5      QueryAdapter.queryListStream.executeQueryAndNotifyController (package:floor/src/adapter/query_adapter.dart:101:28)
E/flutter (19240): #6      QueryAdapter.queryListStream.<anonymous closure> (package:floor/src/adapter/query_adapter.dart:111:55)
E/flutter (19240): #7      _rootRunUnary (dart:async/zone.dart:1192:38)
```

**Comment by mqus** [comment]
This very much sounds like an issue we already had(can't search right now) but it's because your source code is not valid dart, specifically your constructor. Run dart analyzer or flutter analyzer to make sure your code is right before generating the database code ;)

**Comment by mqus** [comment]
One more comment: its double because floor can't derive the type and double is the fallback. The typeconverters feature will change this and will throw an exception instead.

**Comment by mathieurousseau** [comment]
Both android studio and flutter analyze don't complain at all about that code. So I am clueless what's wrong with it.

This being said:
- declaring types in the constructor is fixing the problem of the generation:
```
import 'package:floor/floor.dart';

import 'entity.dart';

@Entity(tableName: 'Consequences')
class Consequence extends ListEntity{

  Consequence(int id, String name, [ String icon = '❓', int points = -1 ]);
  Consequence.named({ int id, String name, String icon = '❓' });
  Consequence.empty({ int id, String icon = '❓', int points = -1 });

}
```
Generates:
```
  static final _consequencesMapper = (Map<String, dynamic> row) => Consequence(
      row['id'] as int,
      row['name'] as String,
      row['icon'] as String,
      row['points'] as int);
```

Now my app is still broken with those constructor:
- Default value of constructor does not work
- Object is showing null on all fields

I'll try to read more where I am failing on the constructor part

**Comment by mqus** [comment]
This seems to be resolved, closing. Please reopen if you disagree :)
