### ISSUE TITLE
floor_generator periodically gets stuck

### ISSUE THREAD

**Issue by proninyaroslav** [vitusortner/floor#408]
**Flutter**: 1.22.1
**Dart**: 2.10.
**floor_generator**: 0.14.0
**build_runner**: 1.10.2
**analyzer**: 0.39.17

Hi. I noticed this exception lately which causes `build_runner` to get stuck.
It seems that this appeared after upgrading `build_runner` from `1.10.1` to `1.10.2` or after upgrading the project to Flutter 1.22 and Dart 2.10.
```
[SEVERE] floor_generator:floor_generator on test/transaction_id_generator_test.dart:

Cycle loading state error
#0      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:177:32)
#1      SetMixin.forEach (dart:collection/set.dart:142:30)
#2      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:117:32)
#3      SetMixin.forEach (dart:collection/set.dart:142:30)
#4      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:117:32)
#5      LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:250:17)
#6      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#7      LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:248:12)
#8      AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1504:25)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _runZoned (dart:async/zone.dart:1630:10)
#12     runZoned (dart:async/zone.dart:1550:10)
#13     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#14     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1490:33)
#15     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1420:28)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#17     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1418:20)
#18     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1006:34)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1967:24)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1890:5)
#21     analysisDriver (package:build_resolvers/src/analysis_driver.dart:62:13)
#22     AnalyzerResolvers._ensureInitialized.<anonymous closure> (package:build_resolvers/src/resolver.dart:224:26)
<asynchronous suspension>
#23     AnalyzerResolvers._ensureInitialized.<anonymous closure> (package:build_resolvers/src/resolver.dart)
#24     AnalyzerResolvers._ensureInitialized (package:build_resolvers/src/resolver.dart:227:6)
#25     AnalyzerResolvers.get (package:build_resolvers/src/resolver.dart:232:11)
#26     PerformanceTrackingResolvers.get.<anonymous closure> (package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart:19:58)
#27     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#28     PerformanceTrackingResolvers.get (package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart:19:16)
#29     BuildStepImpl.resolver (package:build/src/builder/build_step_impl.dart:73:54)
#30     _Builder.build (package:source_gen/src/builder.dart:68:32)
#31     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#32     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#33     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#34     Future.wait (dart:async/future.dart:406:26)
#35     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#36     _rootRun (dart:async/zone.dart:1190:13)
#37     _CustomZone.run (dart:async/zone.dart:1093:19)
#38     _runZoned (dart:async/zone.dart:1630:10)
#39     runZonedGuarded (dart:async/zone.dart:1618:12)
#40     runZoned (dart:async/zone.dart:1547:12)
#41     scopeLogAsync (package:build/src/builder/logging.dart:26:3)
#42     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#43     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:485:19)
#44     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#45     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:483:23)
<asynchronous suspension>
#46     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#47     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#48     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:440:22)
#49     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#50     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:436:17)
#51     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
#52     MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#53     Future.wait (dart:async/future.dart:406:26)
#54     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
#55     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
<asynchronous suspension>
#56     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#57     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
#58     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:315:47)
#59     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#60     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:309:32)
#61     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
#62     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:266:26)
#63     _rootRun (dart:async/zone.dart:1190:13)
#64     _CustomZone.run (dart:async/zone.dart:1093:19)
#65     _runZoned (dart:async/zone.dart:1630:10)
#66     runZonedGuarded (dart:async/zone.dart:1618:12)
#67     runZoned (dart:async/zone.dart:1547:12)
#68     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:261:5)
#69     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:208:24)
#70     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:94:56)
#71     WatchImpl._run.<anonymous closure> (package:build_runner/src/generate/watch_impl.dart:337:14)
<asynchronous suspension>
#72     WatchImpl._run.<anonymous closure> (package:build_runner/src/generate/watch_impl.dart)
#73     WatchImpl._run (package:build_runner/src/generate/watch_impl.dart:355:6)
#74     new WatchImpl (package:build_runner/src/generate/watch_impl.dart:196:20)
#75     _runWatch (package:build_runner/src/generate/watch_impl.dart:127:5)
#76     watch (package:build_runner/src/generate/watch_impl.dart:85:15)
#77     _rootRunUnary (dart:async/zone.dart:1198:47)
#78     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#79     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#80     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#81     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#82     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#83     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#84     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#85     BuildOptions.create (package:build_runner_core/src/generate/options.dart)
#86     _rootRunUnary (dart:async/zone.dart:1198:47)
#87     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#88     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#89     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#90     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#91     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#92     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#93     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#94     TargetGraph.forPackageGraph (package:build_runner_core/src/package_graph/target_graph.dart)
#95     _rootRunUnary (dart:async/zone.dart:1198:47)
#96     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#97     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#98     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#99     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#100    Future._completeWithValue (dart:async/future_impl.dart:529:5)
#101    _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#102    _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#103    _packageBuildConfig (package:build_runner_core/src/package_graph/target_graph.dart)
#104    _rootRunUnary (dart:async/zone.dart:1198:47)
#105    _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#106    _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#107    Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#108    Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#109    Future._completeWithValue (dart:async/future_impl.dart:529:5)
#110    _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#111    _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#112    BuildConfig.fromBuildConfigDir (package:build_config/src/build_config.dart)
#113    _rootRunUnary (dart:async/zone.dart:1198:47)
#114    _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#115    _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#116    Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#117    Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#118    Future._completeWithValue (dart:async/future_impl.dart:529:5)
#119    Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#120    _rootRun (dart:async/zone.dart:1190:13)
#121    _CustomZone.run (dart:async/zone.dart:1093:19)
#122    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#123    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#124    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#125    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#126    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[INFO] 13m 6s elapsed, 11/12 actions completed.
[INFO] 13m 8s elapsed, 11/12 actions completed.
[INFO] 13m 9s elapsed, 11/12 actions completed.
[INFO] 13m 10s elapsed, 11/12 actions completed.
[INFO] 13m 11s elapsed, 11/12 actions completed.
[INFO] 13m 12s elapsed, 11/12 actions completed.
[INFO] 13m 13s elapsed, 11/12 actions completed.
[INFO] 13m 14s elapsed, 11/12 actions completed.
[INFO] 13m 15s elapsed, 11/12 actions completed.
[INFO] 13m 16s elapsed, 11/12 actions completed.
[INFO] 13m 17s elapsed, 11/12 actions completed.
[INFO] 13m 19s elapsed, 11/12 actions completed.
[INFO] 13m 20s elapsed, 11/12 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - freezed:freezed on lib/ui/app.dart
```

**Comment by vitusortner** [comment]
The next release (0.15.0) will come with updated dependencies #406 which should resolve this issue. You can use this version already if you close this repository and directly link it to your project. The new release will be available tonight.

**Comment by vitusortner** [comment]
The release is now available so I'll close this issue. If the problem still occurs, don't hesitate to reopen it.
